<?php
/**
 *---------------------------------------------------------------------------
 *
 *                  T E N C E N T   P R O P R I E T A R Y
 *
 *     COPYRIGHT (c)  2012 BY  TENCENT  CORPORATION.  ALL RIGHTS
 *     RESERVED.   NO  PART  OF THIS PROGRAM  OR  PUBLICATION  MAY
 *     BE  REPRODUCED,   TRANSMITTED,   TRANSCRIBED,   STORED  IN  A
 *     RETRIEVAL SYSTEM, OR TRANSLATED INTO ANY LANGUAGE OR COMPUTER
 *     LANGUAGE IN ANY FORM OR BY ANY MEANS, ELECTRONIC, MECHANICAL,
 *     MAGNETIC,  OPTICAL,  CHEMICAL, MANUAL, OR OTHERWISE,  WITHOUT
 *     THE PRIOR WRITTEN PERMISSION OF :
 *
 *                        TENCENT  CORPORATION
 *
 *       Advertising Platform R&D Team, Advertising Platform & Products
 *       Tencent Ltd.
 *---------------------------------------------------------------------------
 */

/**
 * TMRoutingConfigHandle
 * 解析路由配置文件的类，可以将配置文件的内容解析，并保存成php形式的数组在cache中
 *
 * @package sdk.src.framework.config
 */
class TMRoutingConfigHandle
{
    /**
     * get Config from yml
     *
     * @param string $configFile yml config filepath
     * @return string $content
     */
    public function execute($configFile)
    {
        $routes = $this->parse($configFile);
        $data = array();
        foreach($routes as $name => $routeConfig)
        {
            $r = new ReflectionClass($routeConfig[0]);
            $route = $r->newInstanceArgs($routeConfig[1]);
            
            $data[] = sprintf('$this->routes[\'%s\'] = unserialize(%s);', $name, var_export(serialize($route), true));
        }
        
        return sprintf("<?php\n".
                   "// auto-generated by TMRoutingConfigHandler\n".
                   "// date: %s\n%s\n", date('Y/m/d H:i:s'), implode("\n", $data)
        );
    }

    /**
     * 解析配置文件
     * 
     * @param string $configFile 配置文件路径
     * @return array
     */
    protected function parse($configFile)
    {
        $config = TMYamlCacher::getInstance()->execute($configFile);

        if(!is_array($config))
        {
            return array();
        }
        
        foreach($config as $name => $params)
        {
            $className = isset($params['class']) ? $params['class'] : 'TMRoute';
            $url = isset($params['url']) ? $params['url'] : '/';
            $param = isset($params['param']) ? $params['param'] : array();
            $requirements = isset($params['requirements']) ? $params['requirements'] : array();
            $options = isset($params['options']) ? $params['options'] : array();
            
            $routes[$name] = array($className, array($url, $param, $requirements, $options));   
        }
        
        return $routes;
    }
}